import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { User, UserPreferences, BodyMetrics } from '../types';

interface UserStore {
  user: User | null;
  preferences: UserPreferences;
  bodyMetrics: BodyMetrics;
  isOnboarded: boolean;
  isLoading: boolean;
  setUser: (user: User | null) => void;
  updatePreferences: (prefs: Partial<UserPreferences>) => void;
  updateBodyMetrics: (metrics: Partial<BodyMetrics>) => void;
  setOnboarded: (status: boolean) => void;
  setLoading: (status: boolean) => void;
  initializeDefaultUser: () => void;
  reset: () => void;
}

const defaultUser: User = {
  id: 'default-user',
  name: 'User',
  email: '',
  profileImage: '',
  joinDate: new Date().toISOString(),
  fitnessLevel: 'beginner',
  goals: [],
  exp: 0,
  xp: 0,
  level: 1,
  expToNextLevel: 100,
  streak: 0,
  streakData: {
    currentStreak: 0,
    longestStreak: 0,
    streakDates: []
  },
  preferences: {} as UserPreferences,
  fitnessMetrics: {
    weight: 70,
    height: 170,
    bodyFat: 20,
    muscleMass: 30
  },
  expSystem: {
    totalExp: 0,
    level: 1,
    expToNextLevel: 100,
    expSources: {
      workouts: 0,
      nutrition: 0,
      social: 0
    },
    levelRequirements: { 1: 0, 2: 1000, 3: 2000, 4: 3000, 5: 4000 }
  },
  subscription: {
    tier: 'free',
    status: 'active',
    startDate: new Date().toISOString(),
    autoRenew: false
  },
  avatar: '',
  experience: 0,
  credits: 0,
  lastActive: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const defaultPreferences: UserPreferences = {
  units: 'metric',
  notifications: { workouts: true, nutrition: true, social: true },
  privacy: {
    profileVisible: true,
    shareProgress: true
  },
  theme: 'light',
  soundEffects: true,
  music: true,
  musicGenre: 'pop',
  workoutReminders: true,
  reminderFrequency: 'daily',
  dietaryPreference: 'none',
  calorieGoal: 2000,
  proteinGoal: 100,
  carbGoal: 250,
  fatGoal: 70,
  workoutDifficulty: 'medium',
  workoutDuration: 30,
  preferredWorkoutTypes: [],
  enableHapticFeedback: true,
  enableVoiceGuidance: false,
  voiceLanguage: 'en-US',
  enableBackgroundMusic: true,
  backgroundMusicVolume: 50,
  enableWorkoutTips: true,
  enableNutritionTips: true,
  enableMotivationalQuotes: true,
  enableCommunityFeatures: true,
  privacySettings: {
    shareWorkoutData: true,
    shareNutritionData: true,
    shareProgressPhotos: false,
    shareAchievements: true,
    shareLevel: true,
  },
  appLanguage: 'en',
  measurementSystem: 'metric',
  dateFormat: 'MM/dd/yyyy',
  timeFormat: '12h',
  firstDayOfWeek: 'monday',
  enableAutoSync: true,
  enableWearableIntegration: false,
  enableSpotifyIntegration: false,
  enableAppleHealth: false,
  enableGoogleFit: false,
  enableStrava: false,
  enableFitbit: false,
  enableGarmin: false,
  enableMyFitnessPal: false,
  enableWithings: false,
  enableOura: false,
  enablePolar: false,
  enableSamsungHealth: false,
  enableWhoop: false,
  enableUnderArmour: false,
  enableCronometer: false,
  enableLoseIt: false,
  enableWeightWatchers: false,
  enableNoom: false,
  enablePeloton: false,
  enableZwift: false,
  enableTrainerRoad: false,
  enableWahoo: false,
  enableRuntastic: false,
  enableMapMyRun: false,
  enableNikeRunClub: false,
  enableEndomondo: false,
  enableKomoot: false,
  enableSuunto: false,
  enableCoros: false,
  enableDecathlonCoach: false,
  enableFatSecret: false,
  enableLifesum: false,
  enableYazio: false,
  enableHealthifyMe: false,
  enableFitOn: false,
  enableSweat: false,
  enableAaptiv: false,
  enableCentr: false,
  enableDailyBurn: false,
  enableBeachbody: false,
  enableOpenFoodFacts: false,
  enableNutritionix: false,
  enableBarcodeScanner: false,
  enableVoiceFoodLogging: false,
  enablePhotoFoodLogging: false,
  enableMealPlanning: false,
  enableWaterTracking: true,
  enableMoodTracking: false,
  enableSleepTracking: false,
  enableStressTracking: false,
  enableEnergyTracking: false,
  enableMenstrualCycleTracking: false,
  enablePregnancyMode: false,
  enableNursingMode: false,
  enableBabyTracking: false,
  enableSeniorMode: false,
  enableAccessibilityMode: false,
  enableLowDataMode: false,
  enableBatterySaver: false,
  enableOfflineMode: false,
  enableAutomaticWorkoutDetection: false,
  enableAutomaticMealDetection: false,
  enableAutomaticMoodDetection: false,
  enableAutomaticSleepDetection: false,
  enableAutomaticStressDetection: false,
  enableAutomaticEnergyDetection: false,
  enableAutomaticMenstrualCycleDetection: false,
  enableAutomaticPregnancyDetection: false,
  enableAutomaticNursingDetection: false,
  enableAutomaticBabyDetection: false,
  enableAutomaticSeniorDetection: false,
  enableAutomaticAccessibilityDetection: false,
  enableAutomaticLowDataDetection: false,
  enableAutomaticBatterySaverDetectionDetection: false,
  enableAutomaticOfflineModeDetection: false,
  enableAutomaticThemeDetection: false,
  enableAutomaticLanguageDetection: false,
  enableAutomaticMeasurementSystemDetection: false,
  enableAutomaticDateFormatDetection: false,
  enableAutomaticTimeFormatDetection: false,
  enableAutomaticFirstDayOfWeekDetection: false,
  enableAutomaticAutoSyncDetection: false,
  enableAutomaticWearableIntegrationDetection: false,
  enableAutomaticSpotifyIntegrationDetection: false,
  enableAutomaticAppleHealthDetection: false,
  enableAutomaticGoogleFitDetection: false,
  enableAutomaticStravaDetection: false,
  enableAutomaticFitbitDetection: false,
  enableAutomaticGarminDetection: false,
  enableAutomaticMyFitnessPalDetection: false,
  enableAutomaticWithingsDetection: false,
  enableAutomaticOuraDetection: false,
  enableAutomaticPolarDetection: false,
  enableAutomaticSamsungHealthDetection: false,
  enableAutomaticWhoopDetection: false,
  enableAutomaticUnderArmourDetection: false,
  enableAutomaticCronometerDetection: false,
  enableAutomaticLoseItDetection: false,
  enableAutomaticWeightWatchersDetection: false,
  enableAutomaticNoomDetection: false,
  enableAutomaticPelotonDetection: false,
  enableAutomaticZwiftDetection: false,
  enableAutomaticTrainerRoadDetection: false,
  enableAutomaticWahooDetection: false,
  enableAutomaticRuntasticDetection: false,
  enableAutomaticMapMyRunDetection: false,
  enableAutomaticNikeRunClubDetection: false,
  enableAutomaticEndomondoDetection: false,
  enableAutomaticKomootDetection: false,
  enableAutomaticSuuntoDetection: false,
  enableAutomaticCorosDetection: false,
  enableAutomaticDecathlonCoachDetection: false,
  enableAutomaticFatSecretDetection: false,
  enableAutomaticLifesumDetection: false,
  enableAutomaticYazioDetection: false,
  enableAutomaticHealthifyMeDetection: false,
  enableAutomaticFitOnDetection: false,
  enableAutomaticSweatDetection: false,
  enableAutomaticAaptivDetection: false,
  enableAutomaticCentrDetection: false,
  enableAutomaticDailyBurnDetection: false,
  enableAutomaticBeachbodyDetection: false,
  enableAutomaticOpenFoodFactsDetection: false,
  enableAutomaticNutritionixDetection: false,
  enableAutomaticBarcodeScannerDetection: false,
  enableAutomaticVoiceFoodLoggingDetection: false,
  enableAutomaticPhotoFoodLoggingDetection: false,
  enableAutomaticMealPlanningDetection: false,
  enableAutomaticWaterTrackingDetection: false,
  enableAutomaticMoodTrackingDetection: false,
  enableAutomaticSleepTrackingDetection: false,
  enableAutomaticStressTrackingDetection: false,
  enableAutomaticEnergyTrackingDetection: false,
  enableAutomaticMenstrualCycleTrackingDetection: false,
  enableAutomaticPregnancyModeDetection: false,
  enableAutomaticNursingModeDetection: false,
  enableAutomaticBabyTrackingDetection: false,
  enableAutomaticSeniorModeDetection: false,
  enableAutomaticAccessibilityModeDetection: false,
  enableAutomaticLowDataModeDetection: false
};

const defaultBodyMetrics: BodyMetrics = {
  height: 170,
  weight: 70,
  age: 25,
  gender: 'other',
  bmi: 24.2,
  bodyFatPercentage: 20,
  muscleMass: 30,
  boneDensity: 2.5,
  hydrationLevel: 60,
  metabolicRate: 1500,
  waistCircumference: 80,
  hipCircumference: 100,
  chestCircumference: 90,
  armCircumference: 30,
  thighCircumference: 50,
  calfCircumference: 35,
  neckCircumference: 35,
  wristCircumference: 16,
  ankleCircumference: 22,
  shoulderBreadth: 40,
  handLength: 18,
  footLength: 25,
  bloodPressureSystolic: 120,
  bloodPressureDiastolic: 80,
  restingHeartRate: 70,
  vo2Max: 40,
  gripStrength: 30,
  verticalJump: 50,
  flexibility: 20,
  endurance: 60,
  strength: 50,
  speed: 40,
  agility: 45,
  balance: 50,
  coordination: 55,
  reactionTime: 300,
  power: 60,
  injuryRisk: 'low',
  recoveryRate: 'average',
  stressLevel: 'moderate',
  fatigueLevel: 'low',
  sorenessLevel: 'none',
  mood: 'neutral',
  energyLevel: 'medium',
  sleepQuality: 'good',
  sleepDuration: 8,
  lastUpdated: new Date().toISOString(),
};

export const useUserStore = create<UserStore>()((
  persist(
    (set, get) => ({
      user: null,
      preferences: defaultPreferences,
      bodyMetrics: defaultBodyMetrics,
      isOnboarded: false,
      isLoading: false,

      setUser: (user) => set({ user }),
      updatePreferences: (prefs) => set({
        preferences: { ...get().preferences, ...prefs }
      }),
      updateBodyMetrics: (metrics) => set({
        bodyMetrics: { ...get().bodyMetrics, ...metrics, lastUpdated: new Date().toISOString() }
      }),
      setOnboarded: (status) => set({ isOnboarded: status }),
      setLoading: (status) => set({ isLoading: status }),
      initializeDefaultUser: () => set({
        user: defaultUser,
        preferences: defaultPreferences,
        bodyMetrics: defaultBodyMetrics,
        isOnboarded: false
      }),
      reset: () => set({
        user: null,
        preferences: defaultPreferences,
        bodyMetrics: defaultBodyMetrics,
        isOnboarded: false
      }),
    }),
    {
      name: 'user-storage',
      storage: createJSONStorage(() => AsyncStorage),
    }
  )
));

// Selectors
export const userSelector = (state: UserStore) => state.user;
export const preferencesSelector = (state: UserStore) => state.preferences;
export const bodyMetricsSelector = (state: UserStore) => state.bodyMetrics;
export const onboardedSelector = (state: UserStore) => state.isOnboarded;
export const loadingSelector = (state: UserStore) => state.isLoading;
