name: EAS Production Build
on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build
        required: true
        default: all
        type: choice
        options:
          - all
          - ios
          - android
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: expo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run EAS Build
        run: npx eas-cli@latest build --profile production --platform ${{ github.event.inputs.platform }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
