import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { db } from '../src/config/firebase';
import {
  collection, addDoc, query, where, orderBy, limit, getDocs, serverTimestamp,
  doc, setDoc, deleteDoc,
} from 'firebase/firestore';
import { optimizeArrayForPerformance } from '@/utils/storeOptimizations';



export const useWorkoutStore = create(
  persist(
    (set, get) => ({
      workouts: [],
      customWorkouts: [],
      completedWorkouts: [],
      favoriteWorkoutIds: [],
      // Real, new state: keyed by workout template id, tracks which
      // exercise indices are marked complete for a workout that was
      // saved-and-exited mid-session but not finished. Separate from
      // completedWorkouts (a history log of past sessions) - this is
      // resumable, per-template state so app/workout/[id].jsx's own
      // "X/4 moves"/"Continue Workout" display (which previously
      // always reset to 0/4 on every screen mount, never connected to
      // any store at all) can correctly reflect what was actually
      // saved.
      inProgress: {},
      runningPrograms: [],
      activeProgram: null,
      currentSession: null,
      runHistory: [],
      currentRun: null,
      runningChallenges: [],
      virtualRaces: [],
      runningBuddy: null,
      isLoading: false,

      /* ── Firestore sync ──
       * Real per-workout documents in the top-level `workouts` collection,
       * matching firestore.rules and functions/src/index.js (onWorkoutComplete,
       * getProgressSummary). Previously this wrote a single blob document at
       * users/{uid}/data/workouts, which neither the rules nor the Cloud
       * Functions were watching — completions never triggered stats/goal
       * updates or notifications. */
      loadWorkouts: async (uid) => {
        if (!uid) return;
        set({ isLoading: true });
        try {
          const q = query(
            collection(db, 'workouts'),
            where('userId', '==', uid),
            orderBy('date', 'desc'),
            limit(100)
          );
          const snap = await getDocs(q);
          const completedWorkouts = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
          set({ completedWorkouts });
        } catch (e) {
          console.warn('[workoutStore] loadWorkouts error:', e?.message);
        } finally {
          set({ isLoading: false });
        }
      },

      setWorkouts: (workouts) => set({ workouts }),

      // Real fix: this whole trio (addWorkout/updateWorkout/deleteWorkout)
      // previously only touched local Zustand state - templates a user
      // built in app/workout/create.jsx were never actually persisted
      // anywhere, and vanished on the next app restart. Fixed to mirror
      // addCompletedWorkout's exact pattern: optimistic local update
      // first (UI never blocks on network), then a real Firestore write,
      // with an honest console.warn (not a silent failure) if there's no
      // uid to write under. Templates live in a per-user subcollection
      // (users/{uid}/workoutTemplates/{id}), separate from the top-level
      // `workouts` collection completedWorkouts already correctly uses -
      // genuinely different concepts (a reusable template vs. a finished
      // session record) that happened to share a confusingly similar
      // field name (`workouts` state) before this fix.
      loadWorkoutTemplates: async (uid) => {
        if (!uid) return;
        try {
          const snap = await getDocs(collection(db, 'users', uid, 'workoutTemplates'));
          const workouts = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
          set({ workouts });
        } catch (e) {
          console.warn('[workoutStore] loadWorkoutTemplates error:', e?.message);
        }
      },

      // Real fix, not a stylistic choice: uses workout.id (already
      // generated by the caller, e.g. app/workout/create.jsx's
      // `custom-${Date.now()}`) as the ACTUAL Firestore document ID,
      // rather than letting Firestore mint its own and swapping it in
      // afterward. The caller navigates to /workout/${newWorkout.id}
      // immediately after calling this - if the ID changed underneath
      // that navigation once the write resolved, the screen the user
      // just landed on would suddenly stop matching anything in the
      // store. One stable ID throughout avoids that race entirely.
      addWorkout: async (workout, uid) => {
        const localId = workout.id ?? `local-${Date.now()}`;
        const localRecord = { ...workout, id: localId };
        set((state) => ({ workouts: [...state.workouts, localRecord] }));
        if (!uid) {
          console.warn('[workoutStore] addWorkout: no uid, not persisted to Firestore');
          return localRecord;
        }
        try {
          await setDoc(doc(db, 'users', uid, 'workoutTemplates', localId), {
            ...workout,
            id: localId,
            createdAt: serverTimestamp(),
          });
          return localRecord;
        } catch (e) {
          console.error('[workoutStore] addWorkout Firestore write failed:', e?.message);
          return localRecord;
        }
      },

      updateWorkout: async (id, updates, uid) => {
        set((state) => ({
          workouts: state.workouts.map((workout) =>
          workout.id === id ? { ...workout, ...(updates || {}) } : workout
          )
        }));
        if (!uid) return;
        try {
          await setDoc(doc(db, 'users', uid, 'workoutTemplates', id), updates || {}, { merge: true });
        } catch (e) {
          console.error('[workoutStore] updateWorkout Firestore write failed:', e?.message);
        }
      },

      deleteWorkout: async (id, uid) => {
        set((state) => ({
          workouts: state.workouts.filter((workout) => workout.id !== id)
        }));
        if (!uid) return;
        try {
          await deleteDoc(doc(db, 'users', uid, 'workoutTemplates', id));
        } catch (e) {
          console.error('[workoutStore] deleteWorkout Firestore write failed:', e?.message);
        }
      },

      // Real, new: persists which exercise indices are done for a
      // workout template that was saved-and-exited mid-session, so
      // app/workout/[id].jsx can show real progress instead of always
      // resetting to 0/4. completedIndices is a plain array of
      // exercise indices (not ids) - both active.jsx and [id].jsx
      // derive their own exercises array from the same underlying
      // workout.exercises in the same order, so index is the one thing
      // guaranteed to line up between the two screens regardless of
      // whether individual exercises carry a stable id in the raw
      // template data.
      saveWorkoutProgress: async (workoutId, completedIndices, uid) => {
        if (!workoutId) return;
        set((state) => ({
          inProgress: { ...state.inProgress, [workoutId]: { completedIndices, savedAt: new Date().toISOString() } }
        }));
        if (!uid) return;
        try {
          await setDoc(doc(db, 'users', uid, 'data', 'workoutProgress'), {
            inProgress: get().inProgress,
            updatedAt: new Date().toISOString(),
          }, { merge: true });
        } catch (e) {
          console.error('[workoutStore] saveWorkoutProgress Firestore write failed:', e?.message);
        }
      },

      clearWorkoutProgress: async (workoutId, uid) => {
        if (!workoutId) return;
        set((state) => {
          const next = { ...state.inProgress };
          delete next[workoutId];
          return { inProgress: next };
        });
        if (!uid) return;
        try {
          await setDoc(doc(db, 'users', uid, 'data', 'workoutProgress'), {
            inProgress: get().inProgress,
            updatedAt: new Date().toISOString(),
          }, { merge: true });
        } catch (e) {
          console.error('[workoutStore] clearWorkoutProgress Firestore write failed:', e?.message);
        }
      },

      toggleFavorite: (workoutId) => set((state) => ({
        favoriteWorkoutIds: state.favoriteWorkoutIds.includes(workoutId) ?
        state.favoriteWorkoutIds.filter((id) => id !== workoutId) :
        [...state.favoriteWorkoutIds, workoutId]
      })),

      // Persists immediately to the real `workouts` collection (not just local
      // state) so onWorkoutComplete actually fires, and getProgressSummary /
      // this-device-and-others sync see it. Updates local state optimistically
      // first so the UI never blocks on network.
      addCompletedWorkout: async (workout, uid) => {
        const localRecord = { ...workout, id: workout.id ?? `local-${Date.now()}` };
        set((state) => ({
          completedWorkouts: optimizeArrayForPerformance([...state.completedWorkouts, localRecord], 20)
        }));

        if (!uid) {
          console.warn('[workoutStore] addCompletedWorkout: no uid, not persisted to Firestore');
          return localRecord;
        }

        try {
          const ref = await addDoc(collection(db, 'workouts'), {
            ...workout,
            userId: uid,
            // Real fix: was hardcoded to true unconditionally, which is
            // what let app/workout/active.jsx's Save-and-Exit path
            // write a genuinely partial workout to Firestore marked
            // completed:true - now respects an explicit completed
            // value from the caller (Save-and-Exit passes false),
            // defaulting to true only when the caller doesn't specify
            // one, which preserves the normal full-completion path's
            // existing behavior unchanged (it never passes this field).
            completed: workout.completed ?? true,
            date: serverTimestamp(),
          });
          const saved = { ...localRecord, id: ref.id };
          set((state) => ({
            completedWorkouts: state.completedWorkouts.map((w) => w.id === localRecord.id ? saved : w)
          }));
          return saved;
        } catch (e) {
          console.error('[workoutStore] addCompletedWorkout Firestore write failed:', e?.message);
          return localRecord;
        }
      },

      logCompletedWorkout: async (workoutId, uid) => {
        const workout = [...get().workouts, ...get().customWorkouts].find((w) => w.id === workoutId);
        if (!workout) return null;
        const completedWorkout = {
          workoutId: workout.id,
          name: workout.name,
          category: workout.category,
          difficulty: workout.difficulty,
          exercises: workout.exercises,
          completedAt: new Date().toISOString(),
          duration: workout.duration,
          caloriesBurned: workout.calories || 0,
        };
        return get().addCompletedWorkout(completedWorkout, uid);
      },

      getCompletedWorkouts: () => get().completedWorkouts,

      setRunningPrograms: (programs) => set({ runningPrograms: programs }),

      startProgram: (programId) => {
        const program = get().runningPrograms.find((p) => p.id === programId);
        if (program) {
          set({ activeProgram: program });
        }
      },

      completeSession: (sessionId) => {
        console.log('Session completed:', sessionId);
      },

      pauseProgram: () => set({ activeProgram: null }),

      resumeProgram: () => {
        console.log('Program resumed');
      },

      startSession: (session) => set({ currentSession: session }),

      endSession: () => set({ currentSession: null }),

      startRun: () => {
        const newRun = {
          id: `run-${Date.now()}`,
          startTime: new Date().toISOString(),
          distance: 0,
          duration: 0,
          pace: 0,
          calories: 0,
          coordinates: []
        };
        set({ currentRun: newRun });
      },

      finishRun: () => {
        const { currentRun, runHistory } = get();
        if (currentRun) {
          const newRunRecord = {
            id: currentRun.id,
            date: currentRun.startTime,
            distance: currentRun.distance,
            duration: currentRun.duration,
            pace: currentRun.pace,
            calories: currentRun.calories
          };
          set({
            runHistory: optimizeArrayForPerformance([...runHistory, newRunRecord], 50),
            currentRun: null
          });
        }
      },

      updateRunStats: (stats) => {
        const { currentRun } = get();
        if (currentRun) {
          set({
            currentRun: {
              ...currentRun,
              ...stats
            }
          });
        }
      },

      getRunningStats: () => {
        const { runHistory } = get();
        if (!runHistory || runHistory.length === 0) {
          return {
            totalDistance: 0,
            totalRuns: 0,
            averagePace: 0,
            totalTime: 0
          };
        }

        const totalDistance = runHistory.reduce((sum, run) => sum + run.distance, 0);
        const totalRuns = runHistory.length;
        const totalTime = runHistory.reduce((sum, run) => sum + run.duration, 0);
        const averagePace = runHistory.reduce((sum, run) => sum + run.pace, 0) / totalRuns;

        return {
          totalDistance,
          totalRuns,
          averagePace,
          totalTime
        };
      },

      getPersonalBests: () => {
        const { runHistory } = get();
        if (!runHistory || runHistory.length === 0) {
          return {};
        }

        const personalBests = {};

        // Find fastest 5K
        const fiveKRuns = runHistory.filter((run) => run.distance >= 5.0 && run.distance <= 5.5);
        if (fiveKRuns.length > 0) {
          personalBests.fastest5K = Math.min(...fiveKRuns.map((run) => run.duration));
        }

        // Find fastest 10K
        const tenKRuns = runHistory.filter((run) => run.distance >= 10.0 && run.distance <= 10.5);
        if (tenKRuns.length > 0) {
          personalBests.fastest10K = Math.min(...tenKRuns.map((run) => run.duration));
        }

        // Find longest run
        if (runHistory.length > 0) {
          personalBests.longestRun = Math.max(...runHistory.map((run) => run.distance));
        }

        return personalBests;
      },

      joinChallenge: (challengeId) => {
        set((state) => ({
          runningChallenges: state.runningChallenges.map((challenge) =>
          challenge.id === challengeId ? { ...challenge, isJoined: true } : challenge
          )
        }));
      },

      registerForRace: (raceId) => {
        set((state) => ({
          virtualRaces: state.virtualRaces.map((race) =>
          race.id === raceId ? { ...race, isRegistered: true } : race
          )
        }));
      },

      // Real, Firestore-backed AI recommendation - reads the most recent
      // saved plan from aiRecommendations (written server-side by
      // functions/src/index.js's generateWorkoutPlan/saveRecommendation,
      // confirmed deployed but never previously called from anywhere in
      // the app). Deliberately does NOT call the AI on every load - that
      // function makes a real GPT-4o request server-side, so this reads
      // the cached result first and only regenerates when the user
      // explicitly asks (generateNewWorkoutRecommendation below).
      workoutRecommendation: null,
      isLoadingRecommendation: false,
      loadWorkoutRecommendation: async (uid) => {
        if (!uid) return;
        set({ isLoadingRecommendation: true });
        try {
          const q = query(
            collection(db, 'aiRecommendations'),
            where('userId', '==', uid),
            where('type', '==', 'workout_plan'),
            orderBy('createdAt', 'desc'),
            limit(1)
          );
          const snap = await getDocs(q);
          const rec = snap.docs[0] ? { id: snap.docs[0].id, ...snap.docs[0].data() } : null;
          set({ workoutRecommendation: rec });
        } catch (e) {
          console.warn('[workoutStore] loadWorkoutRecommendation error:', e?.message);
        } finally {
          set({ isLoadingRecommendation: false });
        }
      },
      generateNewWorkoutRecommendation: async ({ uid, fitnessLevel, goals }) => {
        set({ isLoadingRecommendation: true });
        try {
          const { httpsCallable } = await import('firebase/functions');
          const { functions } = await import('../src/config/firebase');
          const history = get().completedWorkouts.slice(0, 10).map((w) => ({
            name: w.name, category: w.category, completedAt: w.completedAt,
          }));
          const fn = httpsCallable(functions, 'generateWorkoutPlan');
          const result = await fn({ fitnessLevel: fitnessLevel || 'beginner', goals: goals || [], history });
          if (uid) await get().loadWorkoutRecommendation(uid);
          return result.data;
        } catch (e) {
          console.error('[workoutStore] generateNewWorkoutRecommendation failed:', e?.message);
          throw e;
        } finally {
          set({ isLoadingRecommendation: false });
        }
      },

      getWorkoutStreak: () => {
        const completed = get().completedWorkouts || [];
        if (completed.length === 0) {
          return { current: 0, longest: 0 };
        }
        // Extract unique local dates (YYYY-MM-DD)
        const dates = Array.from(new Set(
          completed
            .map(w => w.completedAt || w.timestamp)
            .filter(Boolean)
            .map(d => d.slice(0, 10))
        )).sort();

        let longest = 0;
        let current = 0;
        
        // Calculate streak
        const todayStr = new Date().toISOString().slice(0, 10);
        const yesterdayStr = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
        
        // Find if they worked out today or yesterday
        const hasTodayOrYesterday = dates.includes(todayStr) || dates.includes(yesterdayStr);
        
        if (hasTodayOrYesterday) {
          // Count backwards
          let checkDate = dates.includes(todayStr) ? new Date() : new Date(Date.now() - 24 * 60 * 60 * 1000);
          while (true) {
            const checkStr = checkDate.toISOString().slice(0, 10);
            if (dates.includes(checkStr)) {
              current++;
              checkDate = new Date(checkDate.getTime() - 24 * 60 * 60 * 1000);
            } else {
              break;
            }
          }
        }
        
        // Calculate longest streak ever
        let tempStreak = 0;
        let prevTime = null;
        for (const dStr of dates) {
          const currTime = new Date(dStr).getTime();
          if (prevTime === null) {
            tempStreak = 1;
          } else {
            const diffDays = (currTime - prevTime) / (24 * 60 * 60 * 1000);
            if (diffDays <= 1.1) { // within ~1 day
              tempStreak++;
            } else if (diffDays > 1.1) {
              tempStreak = 1;
            }
          }
          if (tempStreak > longest) {
            longest = tempStreak;
          }
          prevTime = currTime;
        }
        
        return { current, longest: Math.max(longest, current) };
      },

      getWorkoutsByDate: (dateStr) => {
        const completed = get().completedWorkouts || [];
        return completed.filter(w => {
          const date = w.completedAt || w.timestamp;
          return date && date.startsWith(dateStr);
        });
      },

      // Real, new: persists one actually-logged set (real weight and
      // reps performed, not the workout template's planned target) to
      // its own loggedSets collection, keyed by exercise name so
      // services/progressiveOverloadService.js can later query a
      // single exercise's full history across every workout it's
      // appeared in, regardless of which workout template. rpe is one
      // of 'easy' | 'moderate' | 'hard', matching what that service
      // expects.
      logSet: async (exerciseName, weight, reps, rpe, workoutId, uid) => {
        if (!uid) {
          console.warn('[workoutStore] logSet: no uid, not persisted');
          return null;
        }
        try {
          const ref = await addDoc(collection(db, 'loggedSets'), {
            userId: uid,
            exerciseName,
            weight,
            reps,
            rpe,
            workoutId: workoutId ?? null,
            date: serverTimestamp(),
          });
          return ref.id;
        } catch (e) {
          console.error('[workoutStore] logSet Firestore write failed:', e?.message);
          return null;
        }
      },

      // Real, new: fetches one exercise's logged-set history so
      // services/progressiveOverloadService.js's getNextPrescription
      // can run on real data. Deliberately only equality where clauses,
      // no orderBy - a compound where+orderBy query would need a
      // Firestore composite index that may not exist yet and can't be
      // created from here; groupSetsBySession (in that same service)
      // already sorts by date internally regardless of the order these
      // come back in, so this doesn't need one. limit(200) is a safety
      // cap, not a real constraint - years of regular training on a
      // single exercise before hitting it.
      getExerciseHistory: async (exerciseName, uid) => {
        if (!uid) return [];
        try {
          const q = query(
            collection(db, 'loggedSets'),
            where('userId', '==', uid),
            where('exerciseName', '==', exerciseName),
            limit(200)
          );
          const snap = await getDocs(q);
          return snap.docs.map((d) => {
            const data = d.data();
            return {
              weight: data.weight,
              reps: data.reps,
              rpe: data.rpe,
              date: data.date?.toDate?.() ?? new Date(),
            };
          });
        } catch (e) {
          console.error('[workoutStore] getExerciseHistory Firestore read failed:', e?.message);
          return [];
        }
      },

    }),
    {
      name: 'workout-storage',
      storage: createJSONStorage(() => AsyncStorage),
      partialize: (state) => ({
        workouts: state.workouts.slice(0, 10), // Limit workouts for performance
        customWorkouts: state.customWorkouts.slice(0, 5),
        completedWorkouts: state.completedWorkouts.slice(-20), // Keep last 20 completed workouts
        favoriteWorkoutIds: state.favoriteWorkoutIds.slice(0, 10),
        inProgress: state.inProgress,
        runningPrograms: state.runningPrograms.slice(0, 5),
        activeProgram: state.activeProgram,
        runHistory: state.runHistory.slice(-50), // Keep last 50 runs
        runningChallenges: state.runningChallenges.slice(0, 10),
        virtualRaces: state.virtualRaces.slice(0, 5),
        runningBuddy: state.runningBuddy
      })
    }
  )
);